extern const Uint8* keys;
const int gasbutton = SDL_SCANCODE_RIGHT;
const int brakebutton = SDL_SCANCODE_LEFT;
const int gearbutton = SDL_SCANCODE_LSHIFT;
const int routeassignbutton = SDL_SCANCODE_LCTRL;
const int numberbuttons[10] = {SDL_SCANCODE_0, SDL_SCANCODE_1, SDL_SCANCODE_2, SDL_SCANCODE_3, SDL_SCANCODE_4, SDL_SCANCODE_5, SDL_SCANCODE_6, SDL_SCANCODE_7, SDL_SCANCODE_8, SDL_SCANCODE_9};
const int loadbutton = SDL_SCANCODE_L;
const int unloadbutton = SDL_SCANCODE_U;
const int couplebutton = SDL_SCANCODE_G;
const int leftpanbutton = SDL_SCANCODE_A;
const int rightpanbutton = SDL_SCANCODE_D;
const int uppanbutton = SDL_SCANCODE_W;
const int downpanbutton = SDL_SCANCODE_S;

const int SCREEN_WIDTH = 1000;
const int SCREEN_HEIGHT = 800;
const int MAP_WIDTH = SCREEN_WIDTH*64;
const int MAP_HEIGHT = SCREEN_HEIGHT*64;
const double pi = 3.141592653589793238;
const float g = 9.8;
const float normalgauge = 1.435;
